name: Build PyTorch from Source

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-pytorch:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up dependencies
        run: sudo apt-get update && sudo apt-get install -y wget git ninja-build

      - name: Run custom build script
        run: |
          chmod +x build_pytorch.sh
          ./build_pytorch.sh \
            --cuda-version "12.1" \
            --cudnn-version "8.9.7.29" \
            --pytorch-version "v2.3.1"
        
      - name: Upload wheel artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-wheel
          path: dist/*.whl
