name: Build PyTorch + TorchVision + TorchAudio from Source with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-pytorch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
          docker build -t my-pytorch-builder:latest .

      - name: Prepare dist folder
        run: mkdir -p dist

      - name: Run Docker Container to Build Wheels
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/dist:/wheelhouse \
            my-pytorch-builder:latest

      - name: Upload Wheels
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-vision-audio-wheels
          path: dist
