name: Build PyTorch from Source with Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-pytorch:
    # GitHub-hosted runner with Docker installed
    runs-on: ubuntu-latest

    steps:
      # 1) Check out this repo so we have access to the Dockerfile (and any needed scripts).
      - uses: actions/checkout@v4

      # 2) Build the Docker image
      #    - We assume the Dockerfile is in the repository root.
      #    - Tag the image as "my-pytorch-builder:latest" (or anything you like).
      - name: Build Docker Image
        run: |
          docker build -t my-pytorch-builder:latest .

      # 3) Create a dist/ folder on the runner (just to be safe).
      - name: Prepare dist folder
        run: mkdir -p dist

      # 4) Run the Docker container.
      #    - We mount the runner’s "dist" folder into the container’s "/wheelhouse".
      #    - The Dockerfile’s CMD or final step places the .whl in /wheelhouse.
      - name: Run Docker Container to Build PyTorch Wheel
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/dist:/wheelhouse \
            my-pytorch-builder:latest

      # 5) Upload the wheel(s) from the dist/ folder as an artifact named "pytorch-wheel".
      - name: Upload PyTorch Wheel
        uses: actions/upload-artifact@v4
        with:
          name: pytorch-wheel
          path: dist
